<?php

namespace Seveinfo\FrontCarteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
		public function premiereRechercheNom($partNom){
        //modification de la varible d'entre
        $modifPartNom = '%'.$partNom.'%';
        //création de la coquille de requete
        $qb = $this­>_em­>createQueryBuilder();
        
        //création de la requete
        $qb ­>select('c')
            ­>from('SeveinfoFrontCarteBundle:Client', 'c')  
            ­>where('c.nom like :partnom')    
            ­>setParameter('partnom', $modifPartNom);
        
        //retour du résultat
        return $qb­>getQuery()­>getResult();
    	}
}
